<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJEODsd5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJEODsd5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJEODsd5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJEODsd5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJEODsd5\App_KernelDevDebugContainer([
    'container.build_hash' => 'JEODsd5',
    'container.build_id' => '8797e54a',
    'container.build_time' => 1599421260,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJEODsd5');
